source/_includes/custom/header.html

This should fix the redirect search issue. More info: https://twitter.com/octopress/status/546528904115404800

Fix site search issue after Google update

---

source/devcon-2015-prospectus/index.html

Don't worry, Han still shoots first, we're not making a Special Edition or anything here.

Updates for the DevCon Prospectus

---

source/_posts/2016-07-13-advanced-debugging.markdown

Relates to #43. I made a minor grammatical mistake which I unfortunately caught a little late.  This pull request fixes it.

Advanced Debugging Blog - fixed a minor typo

---

source/_posts/2016-07-13-difficult-debugging.markdown

Based on feedback I've decided that `Difficult Debugging` is a more meaningful title.

Renamed to Difficult Debugging

---

source/_posts/2016-11-11-clara-rules-joins-cerner-open-source.markdown

Adding an announcement for clara-rules OSS project.

Adding clara-rules OSS

---

source/_posts/2017-02-15-beadledom-simple-java-framework-for-building-rest-apis.markdown

Blog post announcing Beadledom.

Announcement of Beadledom 

---

source/_posts/2017-03-10-version-databag---a-chef-release-process.markdown

JIRA: https://jira3.cerner.com/browse/CULTURE-20
Project: https://jira3.cerner.com/browse/OSSPRJCTS-6
Note, this should not be merged until the project is available!

Adding post for Chef Version Databag cookbook

---

source/_includes/custom/search.html

Remove ability to press return on search field

---

source/open_source/index.html

Updating case for canadarm logo

---

source/_posts/2017-07-14-managing-splunk-knowledge.markdown

Adding _Managing Splunk's Knowledge_ blog post from @bbaugher.

Adding Managing Splunk's Knowledge post

---

source/_posts/2017-08-28-structure-matters-how-cerner-handled-too-much-health-data-in-hbase.markdown

Basing this on changes originally by #81 and applied updates. Targeting to be published today (28th).

Adding "How Cerner Handled Too Much Health Data in HBase" blog

---

source/_posts/2017-12-19-2-to-the-5th-coding-competition-2017.markdown

Opening up this PR for @cchesser 
Attaching a copy of the preview as well.

Initial draft of 2^5th blog

---

source/_posts/2018-02-06-cerner-open-sources-its-kafka-utilities.markdown

Adding Kafka Blog

---

source/_posts/2018-03-13-cerner-and-icontrol.markdown

Adding Cerner and iControl blog

---

source/culture/index.html

Updating text for the culture page as per Lindsey.

Updating text for culture page

---

_config.yml
source/_includes/asides/follow.html
source/tech_talks/index.html

A few updates as per Melanie and Lindsey. You can follow us directly from the site now and see updated youtube content.

Adding follow us and updating tech talks

---

source/_posts/2019-02-08-devcon-recap.markdown

Adding DevCon blog post for publishing 2019-02-08

---

source/_posts/2019-08-09-ccl-unit-and-ccl-testing-released-to-open-source.markdown

Adding CCL Unit/CCL Testing blog post

---

UPDATING.markdown
source/_posts/2019-10-08-introducing-f-twelve-an-open-source-dev-console.markdown

This is my first Blog publish so let me know if i  messed up anything with converting the formats. 
Took a stab at branch deploying it, but i need to resolve some jekyll relative path resolution issues still
https://cerner-engineering-blog-tmp.s3-us-west-2.amazonaws.com/test-branch-deploy-blog/blog/introducing-f-twelve-an-open-source-dev-console/index.html

Add md for f12 post

---

source/_posts/2020-02-24-shipit-xvii.md

Update authors for ShipIt XVII post

---

Dockerfile
app.json
heroku.yml

Heroku PR  Deployments

---

content/post/we-are-back-w-new-look/index.md

New blog post sharing about the uplift to Hugo with a new theme.

Adding blog post for our new site format for 8/4 publish

---

content/open-source/index.html
content/tech-talks.html
themes/eh-theme/package.json
themes/eh-theme/yarn.lock

Applying some additional changes for the site:
* #152 to fix OSS links on the page
* #153 to add DevCon 2020 playlist
* Upgrade serialize-javascript for vulnerabilities corrections

Adding DevCon 2020 playlist, Fixing OSS links, upgrading serialize-javascript

---

heroku.yml

This will assist in review blog posts with future publish date/time.

Issue #159: Adding buildFuture for preview builds

---

.github/workflows/gh-pages.yml
content/post/2-to-the-5th-coding-competition-2017/index.md
content/post/pi-day-2019-build-your-own-alarm-system/index.md

Upgrading Hugo, which resulted in migrating some of the twitter shortcode references.

Updating to Hugo 0.96
